name: iOS CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install gems
        run: bundle install

      # ---------------------
      # Install certificate
      # ---------------------
      - name: Import certificate
        run: |
          echo "$IOS_P12_BASE64" | base64 --decode > ios_cert.p12
          security create-keychain -p "" build.keychain
          security import ios_cert.p12 -P "$IOS_P12_PASSWORD" -A -k build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
        env:
          IOS_P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
          IOS_P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}

      # ---------------------
      # Install provisioning profile
      # ---------------------
      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          UUID=$(grep -a -Eo "([A-F0-9]{8}(-[A-F0-9]{4}){4}[A-F0-9]{12})" profile.mobileprovision | head -1)
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
        env:
          PROFILE_BASE64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}

      # ---------------------
      # Install Firebase CLI
      # ---------------------
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # ---------------------
      # Run Fastlane lane
      # ---------------------
      - name: Run Fastlane CI lane
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID }}
          FIREBASE_TESTERS: ${{ secrets.FIREBASE_TESTERS }}
          CI: "true"
        run: |
          bundle exec fastlane ci_dev  # hoáº·c ci_adhoc / ci_prod
